<a href="https://colab.research.google.com/github/koeyhnim/-/blob/1%EC%9D%BC%EC%B0%A8/1_1_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EB%B9%A0%EB%A5%B4%EA%B2%8C_%EC%A0%95%EB%A6%AC%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **머신러닝 빠르게 정리하기**

# **1.환경준비**

* 라이브러리 Import

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split              # 데이터 분할
from sklearn.metrics import *                                     # 평가
from sklearn.preprocessing import StandardScaler, MinMaxScaler    # 스케일링

# **2.Regression : Advertising**

## (1) 데이터 전처리

### 1) 데이터 준비

In [10]:
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/advertising.csv'
data1 = pd.read_csv(path)
data1.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [11]:
# x, y 나누기
target = 'Sales'
x = data1.drop(target, axis=1)
y = data1.loc[:, target]

### 2) 가변수화

### 3) 데이터분할

In [12]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = .3  , random_state = 20)

### 4) Scaling
* 필요할 때만 스케일링 : KNN, SVM, K-Means, Deep Learning

In [13]:
scaler = MinMaxScaler()
x_train_s = scaler.fit_transform(x_train)
x_val_s = scaler.transform(x_val)

## (2) 모델링
* 필요한 함수들 불러오기
* 모델 선언
* 학습
* 예측
* 성능 검증

In [15]:
# LinearRegression으로 모델링을 수행합니다.
from sklearn.linear_model import LinearRegression

### 1) 모델 선언

In [16]:
model = LinearRegression()

### 2) 학습

In [17]:
model.fit(x_train_s, y_train)

LinearRegression()

### 3) 검증 : 예측

In [18]:
pred = model.predict(x_val_s)
pred

array([17.96608868, 19.1997377 ,  9.0111069 , 15.55619518, 19.46246422,
       17.05922726, 12.09692612,  8.34473812, 21.62975941,  5.73003159,
       12.06983133, 14.04389523, 17.07081046, 11.45556076, 20.78320683,
       24.60891245,  5.83166235, 13.16249899,  8.36390598,  4.89524227,
       19.7892101 , 16.28849844, 17.29878585, 23.19655117, 20.84927704,
        8.90828202, 14.91003685, 11.24392212, 13.19715001, 15.3050095 ,
        7.72821324, 19.78613939,  9.41817976, 10.94073342, 23.8769123 ,
       15.09614864, 10.29705254,  9.09217209, 11.97324787, 13.84999355,
       16.30071518, 12.12194608, 19.18769242, 18.06856111, 13.51058739,
       18.2742912 , 13.48152824, 13.35165101, 21.01917496, 11.13171383,
       11.16365802,  8.21541903,  9.52770803, 18.34720107, 12.02079148,
       12.88451603, 21.37661567, 11.81392393, 11.02689706, 17.25717112])

### 4) 검증 : 평가
만든 모델은 얼마나 정확한지 검증해 봅시다.

In [19]:
mean_absolute_error(y_val, pred)

1.5030135035019552

-----

# **3.Classification : 대학원 지원**

## (1) 데이터 전처리

### 1) 데이터 준비

In [20]:
path = "https://raw.githubusercontent.com/DA4BAM/dataset/master/Graduate_apply.csv"
data2 = pd.read_csv(path)
data2.head()

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [21]:
# x, y 분할
target = 'admit'
x = data2.drop(target, axis=1)
y = data2.loc[:, target]

### 2) 가변수화

In [22]:
cat_cols = ['rank']
x = pd.get_dummies(x, columns = cat_cols, drop_first = True)

### 3) 데이터분할

In [23]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = .3, random_state = 20)

### 4) Scaling
* 필요할 때만 스케일링 : KNN, SVM, K-Means, Deep Learning

In [24]:
scaler = MinMaxScaler()
x_train_s = scaler.fit_transform(x_train)
x_val_s = scaler.transform(x_val)

## (2) 모델링
* 필요한 함수들 불러오기
* 모델 선언
* 학습
* 예측
* 성능 검증

In [25]:
# DecisionTreeClassifier로 모델링을 수행합니다.
from sklearn.tree import DecisionTreeClassifier

### 1) 모델 선언

In [26]:
model = DecisionTreeClassifier()

### 2) 학습

In [27]:
model.fit(x_train_s, y_train)

DecisionTreeClassifier()

### 3) 검증 : 예측

In [28]:
pred = model.predict(x_val_s)
pred

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0])

### 4) 검증 : 평가
만든 모델은 얼마나 정확한지 검증해 봅시다.

In [29]:
accuracy_score(y_val, pred)

0.55